import "./globals.css";
import localFont from "next/font/local";
import { AuthProvider } from "@/components/Context/AuthContext";
import { ThemeProvider } from "@/components/Context/theme-provider";
import { Toaster } from "@/components/ui/sonner";

const manrope = localFont({
  src: "../../public/fonts/Manrope-VariableFont_wght.ttf",
  display: "swap",
  variable: "--font-manrope",
  weight: "200 800",
});

export const metadata = {
  title: "School Management",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={manrope.variable} suppressHydrationWarning>
      <body className="overflow-x-hidden bg-black/2">
        <AuthProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </AuthProvider>
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
