import "./globals.css";
import { Manrope } from "next/font/google";
import { AuthProvider } from '@/components/Context/AuthContext';
import { ThemeProvider } from "@/components/Context/theme-provider"



const manrope = Manrope({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={manrope.className}>
      <body className="overflow-x-hidden bg-black/2" suppressHydrationWarning>
          <AuthProvider>
            <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
                    {children}
            </ThemeProvider>
          </AuthProvider>
      </body>
    </html>
  );
}
