import "./globals.css";
import { Manrope } from "next/font/google";
import { AuthProvider } from "@/components/Context/AuthContext";
import { ThemeProvider } from "@/components/Context/theme-provider";
import { Toaster } from "@/components/ui/sonner";

const manrope = Manrope({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={manrope.className} suppressHydrationWarning>
      <body className="overflow-x-hidden bg-black/2">
        <AuthProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </AuthProvider>
        <Toaster
          position="top-center"
          offset={{
            top: 24,
            left: 40,
            right: 20,
          }}
        />
      </body>
    </html>
  );
}
